/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosRouteImport } from './routes/pos'
import { Route as MobileSigninRouteImport } from './routes/mobile-signin'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardProduitsIndexRouteImport } from './routes/_dashboard/produits/index'
import { Route as DashboardParametresIndexRouteImport } from './routes/_dashboard/parametres/index'
import { Route as DashboardEmployesIndexRouteImport } from './routes/_dashboard/employes/index'
import { Route as DashboardDepensesIndexRouteImport } from './routes/_dashboard/depenses/index'
import { Route as DashboardCommandesIndexRouteImport } from './routes/_dashboard/commandes/index'
import { Route as DashboardClientsIndexRouteImport } from './routes/_dashboard/clients/index'
import { Route as DashboardanalyticsIndexRouteImport } from './routes/_dashboard/(analytics)/index'
import { Route as DashboardProduitsCreateRouteImport } from './routes/_dashboard/produits/create'
import { Route as DashboardProduitsSlugRouteImport } from './routes/_dashboard/produits/$slug'
import { Route as DashboardCommandesSlugRouteImport } from './routes/_dashboard/commandes/$slug'
import { Route as DashboardClientsSlugRouteImport } from './routes/_dashboard/clients/$slug'

const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileSigninRoute = MobileSigninRouteImport.update({
  id: '/mobile-signin',
  path: '/mobile-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProduitsIndexRoute = DashboardProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParametresIndexRoute =
  DashboardParametresIndexRouteImport.update({
    id: '/parametres/',
    path: '/parametres/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmployesIndexRoute = DashboardEmployesIndexRouteImport.update({
  id: '/employes/',
  path: '/employes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepensesIndexRoute = DashboardDepensesIndexRouteImport.update({
  id: '/depenses/',
  path: '/depenses/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommandesIndexRoute = DashboardCommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardanalyticsIndexRoute = DashboardanalyticsIndexRouteImport.update({
  id: '/(analytics)/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProduitsCreateRoute = DashboardProduitsCreateRouteImport.update({
  id: '/produits/create',
  path: '/produits/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProduitsSlugRoute = DashboardProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommandesSlugRoute = DashboardCommandesSlugRouteImport.update({
  id: '/commandes/$slug',
  path: '/commandes/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsSlugRoute = DashboardClientsSlugRouteImport.update({
  id: '/clients/$slug',
  path: '/clients/$slug',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/magic-link': typeof MagicLinkRoute
  '/mobile-signin': typeof MobileSigninRoute
  '/pos': typeof PosRoute
  '/clients/$slug': typeof DashboardClientsSlugRoute
  '/commandes/$slug': typeof DashboardCommandesSlugRoute
  '/produits/$slug': typeof DashboardProduitsSlugRoute
  '/produits/create': typeof DashboardProduitsCreateRoute
  '/': typeof DashboardanalyticsIndexRoute
  '/clients': typeof DashboardClientsIndexRoute
  '/commandes': typeof DashboardCommandesIndexRoute
  '/depenses': typeof DashboardDepensesIndexRoute
  '/employes': typeof DashboardEmployesIndexRoute
  '/parametres': typeof DashboardParametresIndexRoute
  '/produits': typeof DashboardProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/magic-link': typeof MagicLinkRoute
  '/mobile-signin': typeof MobileSigninRoute
  '/pos': typeof PosRoute
  '/clients/$slug': typeof DashboardClientsSlugRoute
  '/commandes/$slug': typeof DashboardCommandesSlugRoute
  '/produits/$slug': typeof DashboardProduitsSlugRoute
  '/produits/create': typeof DashboardProduitsCreateRoute
  '/': typeof DashboardanalyticsIndexRoute
  '/clients': typeof DashboardClientsIndexRoute
  '/commandes': typeof DashboardCommandesIndexRoute
  '/depenses': typeof DashboardDepensesIndexRoute
  '/employes': typeof DashboardEmployesIndexRoute
  '/parametres': typeof DashboardParametresIndexRoute
  '/produits': typeof DashboardProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/magic-link': typeof MagicLinkRoute
  '/mobile-signin': typeof MobileSigninRoute
  '/pos': typeof PosRoute
  '/_dashboard/clients/$slug': typeof DashboardClientsSlugRoute
  '/_dashboard/commandes/$slug': typeof DashboardCommandesSlugRoute
  '/_dashboard/produits/$slug': typeof DashboardProduitsSlugRoute
  '/_dashboard/produits/create': typeof DashboardProduitsCreateRoute
  '/_dashboard/(analytics)/': typeof DashboardanalyticsIndexRoute
  '/_dashboard/clients/': typeof DashboardClientsIndexRoute
  '/_dashboard/commandes/': typeof DashboardCommandesIndexRoute
  '/_dashboard/depenses/': typeof DashboardDepensesIndexRoute
  '/_dashboard/employes/': typeof DashboardEmployesIndexRoute
  '/_dashboard/parametres/': typeof DashboardParametresIndexRoute
  '/_dashboard/produits/': typeof DashboardProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/magic-link'
    | '/mobile-signin'
    | '/pos'
    | '/clients/$slug'
    | '/commandes/$slug'
    | '/produits/$slug'
    | '/produits/create'
    | '/'
    | '/clients'
    | '/commandes'
    | '/depenses'
    | '/employes'
    | '/parametres'
    | '/produits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/magic-link'
    | '/mobile-signin'
    | '/pos'
    | '/clients/$slug'
    | '/commandes/$slug'
    | '/produits/$slug'
    | '/produits/create'
    | '/'
    | '/clients'
    | '/commandes'
    | '/depenses'
    | '/employes'
    | '/parametres'
    | '/produits'
  id:
    | '__root__'
    | '/_dashboard'
    | '/magic-link'
    | '/mobile-signin'
    | '/pos'
    | '/_dashboard/clients/$slug'
    | '/_dashboard/commandes/$slug'
    | '/_dashboard/produits/$slug'
    | '/_dashboard/produits/create'
    | '/_dashboard/(analytics)/'
    | '/_dashboard/clients/'
    | '/_dashboard/commandes/'
    | '/_dashboard/depenses/'
    | '/_dashboard/employes/'
    | '/_dashboard/parametres/'
    | '/_dashboard/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  MagicLinkRoute: typeof MagicLinkRoute
  MobileSigninRoute: typeof MobileSigninRoute
  PosRoute: typeof PosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-signin': {
      id: '/mobile-signin'
      path: '/mobile-signin'
      fullPath: '/mobile-signin'
      preLoaderRoute: typeof MobileSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/produits/': {
      id: '/_dashboard/produits/'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof DashboardProduitsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/parametres/': {
      id: '/_dashboard/parametres/'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof DashboardParametresIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/employes/': {
      id: '/_dashboard/employes/'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof DashboardEmployesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/depenses/': {
      id: '/_dashboard/depenses/'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DashboardDepensesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/commandes/': {
      id: '/_dashboard/commandes/'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof DashboardCommandesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients/': {
      id: '/_dashboard/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/(analytics)/': {
      id: '/_dashboard/(analytics)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardanalyticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/produits/create': {
      id: '/_dashboard/produits/create'
      path: '/produits/create'
      fullPath: '/produits/create'
      preLoaderRoute: typeof DashboardProduitsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/produits/$slug': {
      id: '/_dashboard/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof DashboardProduitsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/commandes/$slug': {
      id: '/_dashboard/commandes/$slug'
      path: '/commandes/$slug'
      fullPath: '/commandes/$slug'
      preLoaderRoute: typeof DashboardCommandesSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients/$slug': {
      id: '/_dashboard/clients/$slug'
      path: '/clients/$slug'
      fullPath: '/clients/$slug'
      preLoaderRoute: typeof DashboardClientsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClientsSlugRoute: typeof DashboardClientsSlugRoute
  DashboardCommandesSlugRoute: typeof DashboardCommandesSlugRoute
  DashboardProduitsSlugRoute: typeof DashboardProduitsSlugRoute
  DashboardProduitsCreateRoute: typeof DashboardProduitsCreateRoute
  DashboardanalyticsIndexRoute: typeof DashboardanalyticsIndexRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
  DashboardCommandesIndexRoute: typeof DashboardCommandesIndexRoute
  DashboardDepensesIndexRoute: typeof DashboardDepensesIndexRoute
  DashboardEmployesIndexRoute: typeof DashboardEmployesIndexRoute
  DashboardParametresIndexRoute: typeof DashboardParametresIndexRoute
  DashboardProduitsIndexRoute: typeof DashboardProduitsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClientsSlugRoute: DashboardClientsSlugRoute,
  DashboardCommandesSlugRoute: DashboardCommandesSlugRoute,
  DashboardProduitsSlugRoute: DashboardProduitsSlugRoute,
  DashboardProduitsCreateRoute: DashboardProduitsCreateRoute,
  DashboardanalyticsIndexRoute: DashboardanalyticsIndexRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
  DashboardCommandesIndexRoute: DashboardCommandesIndexRoute,
  DashboardDepensesIndexRoute: DashboardDepensesIndexRoute,
  DashboardEmployesIndexRoute: DashboardEmployesIndexRoute,
  DashboardParametresIndexRoute: DashboardParametresIndexRoute,
  DashboardProduitsIndexRoute: DashboardProduitsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  MagicLinkRoute: MagicLinkRoute,
  MobileSigninRoute: MobileSigninRoute,
  PosRoute: PosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
