/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LivestoreRouteImport } from './routes/livestore'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardProduitsIndexRouteImport } from './routes/_dashboard/produits/index'
import { Route as DashboardProduitsCreateRouteImport } from './routes/_dashboard/produits/create'
import { Route as DashboardProduitsSlugRouteImport } from './routes/_dashboard/produits/$slug'
import { Route as DashboardCommandesSlugRouteImport } from './routes/_dashboard/commandes/$slug'
import { Route as DashboardClientsSlugRouteImport } from './routes/_dashboard/clients/$slug'

const LivestoreRoute = LivestoreRouteImport.update({
  id: '/livestore',
  path: '/livestore',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProduitsIndexRoute = DashboardProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProduitsCreateRoute = DashboardProduitsCreateRouteImport.update({
  id: '/produits/create',
  path: '/produits/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProduitsSlugRoute = DashboardProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommandesSlugRoute = DashboardCommandesSlugRouteImport.update({
  id: '/commandes/$slug',
  path: '/commandes/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsSlugRoute = DashboardClientsSlugRouteImport.update({
  id: '/clients/$slug',
  path: '/clients/$slug',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/debug': typeof DebugRoute
  '/livestore': typeof LivestoreRoute
  '/clients/$slug': typeof DashboardClientsSlugRoute
  '/commandes/$slug': typeof DashboardCommandesSlugRoute
  '/produits/$slug': typeof DashboardProduitsSlugRoute
  '/produits/create': typeof DashboardProduitsCreateRoute
  '/produits': typeof DashboardProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/debug': typeof DebugRoute
  '/livestore': typeof LivestoreRoute
  '/clients/$slug': typeof DashboardClientsSlugRoute
  '/commandes/$slug': typeof DashboardCommandesSlugRoute
  '/produits/$slug': typeof DashboardProduitsSlugRoute
  '/produits/create': typeof DashboardProduitsCreateRoute
  '/produits': typeof DashboardProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/debug': typeof DebugRoute
  '/livestore': typeof LivestoreRoute
  '/_dashboard/clients/$slug': typeof DashboardClientsSlugRoute
  '/_dashboard/commandes/$slug': typeof DashboardCommandesSlugRoute
  '/_dashboard/produits/$slug': typeof DashboardProduitsSlugRoute
  '/_dashboard/produits/create': typeof DashboardProduitsCreateRoute
  '/_dashboard/produits/': typeof DashboardProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/debug'
    | '/livestore'
    | '/clients/$slug'
    | '/commandes/$slug'
    | '/produits/$slug'
    | '/produits/create'
    | '/produits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/debug'
    | '/livestore'
    | '/clients/$slug'
    | '/commandes/$slug'
    | '/produits/$slug'
    | '/produits/create'
    | '/produits'
  id:
    | '__root__'
    | '/_dashboard'
    | '/debug'
    | '/livestore'
    | '/_dashboard/clients/$slug'
    | '/_dashboard/commandes/$slug'
    | '/_dashboard/produits/$slug'
    | '/_dashboard/produits/create'
    | '/_dashboard/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  DebugRoute: typeof DebugRoute
  LivestoreRoute: typeof LivestoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/livestore': {
      id: '/livestore'
      path: '/livestore'
      fullPath: '/livestore'
      preLoaderRoute: typeof LivestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/produits/': {
      id: '/_dashboard/produits/'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof DashboardProduitsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/produits/create': {
      id: '/_dashboard/produits/create'
      path: '/produits/create'
      fullPath: '/produits/create'
      preLoaderRoute: typeof DashboardProduitsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/produits/$slug': {
      id: '/_dashboard/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof DashboardProduitsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/commandes/$slug': {
      id: '/_dashboard/commandes/$slug'
      path: '/commandes/$slug'
      fullPath: '/commandes/$slug'
      preLoaderRoute: typeof DashboardCommandesSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients/$slug': {
      id: '/_dashboard/clients/$slug'
      path: '/clients/$slug'
      fullPath: '/clients/$slug'
      preLoaderRoute: typeof DashboardClientsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClientsSlugRoute: typeof DashboardClientsSlugRoute
  DashboardCommandesSlugRoute: typeof DashboardCommandesSlugRoute
  DashboardProduitsSlugRoute: typeof DashboardProduitsSlugRoute
  DashboardProduitsCreateRoute: typeof DashboardProduitsCreateRoute
  DashboardProduitsIndexRoute: typeof DashboardProduitsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClientsSlugRoute: DashboardClientsSlugRoute,
  DashboardCommandesSlugRoute: DashboardCommandesSlugRoute,
  DashboardProduitsSlugRoute: DashboardProduitsSlugRoute,
  DashboardProduitsCreateRoute: DashboardProduitsCreateRoute,
  DashboardProduitsIndexRoute: DashboardProduitsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  DebugRoute: DebugRoute,
  LivestoreRoute: LivestoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
